name = "iqair-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]


[[kv_namespaces]]
binding = "STATIONS_CACHE"
id = "6efc820c517d42bcbb39f6a485f4cf85"

[vars]
DEFAULT_DATA_SOURCE = "central-pollution-control-board"
CACHE_TTL_SECONDS = "1209600"

[dev]
port = 8787
local_protocol = "http"
